# Site settings
title: Sercan Dede - Portfolio
email: sercan0dede@gmail.com
description: >
  Website showcasing Sercan Dede's portfolio.
url: "https://xsercanx.github.io/"
github_username:  xsercanx